# Data merging and Cleaning
##### After briefly checking the dataset, I decided to merge the dataset by company in order to clean it since each company has their own value 
### about the requirement dataset : 
- ```net_manager``` : code of regional network manager
- ```Purchase_area```: code of the area where the energy is purchased
- ```street```: Name of the street
- ```zipcode_from``` and ```zipcode_to```: 2 columns for the range of zipcodes covered, 4 numbers and 2 letters
- ```city```: Name of the city
- ```num_connections```: Number of connections in the range of zipcodes
- ```delivery_perc```: percentage of the net consumption of electricity or gas. The lower, the
more energy was given back to the grid (for example if you have solar panels)
- ```perc_of_active_connections```: Percentage of active connections in the zipcode range
- ```type_of_connection```: principal type of connection in the zipcode range. For electricity
is # fuses X # amp√®re. For gas is G4, G6, G10, G16, G25
- ```type_conn_perc```: percentage of presence of the principal type of connection in the
zipcode range
- ```annual_consume```: Annual consume. Kwh for electricity, m3 for gas
- ```annual_consume_lowtarif_perc```: Percentage of consume during the low tarif hours.
From 10 p.m. to 7 a.m. and during weekends.
- ```smartmeter_perc```: percentage of smartmeters in the zipcode ranges

### Summary of cleaning steps
- Merge the data by companies.
- re-split by type and year

In [1]:
import pandas as pd

In [2]:
def load_and_process_data(path, used_columns, company, year, data_type):
    df = pd.read_csv(path, usecols=used_columns)
    df['Year'] = year
    df['Type'] = data_type
    df['Company'] = company
    return df

def load_all_datasets(base_path, used_columns):
    companies = ['Coteq', 'Stedin', 'Westland-infra']  # Updated company names
    years = [2018, 2019, 2020]
    data_types = ['Electricity', 'Gas']

    all_datasets = []

    for company in companies:
        for year in years:
            for data_type in data_types:
                path = f'{base_path}/{data_type}/{company.lower()}_{data_type.lower()}_{year}.csv'  # Using lowercase in the file path
                dataset = load_and_process_data(path, used_columns, company, year, data_type)
                all_datasets.append(dataset)

    return pd.concat(all_datasets, ignore_index=True)

# Example usage:
base_path = 'C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/EEET2574_Assignment2_data'
used_columns = ['net_manager', 'purchase_area', 'street', 'zipcode_from', 'zipcode_to', 'city', 'num_connections', 'delivery_perc', 'perc_of_active_connections', 'type_conn_perc', 'type_of_connection', 'annual_consume', 'annual_consume_lowtarif_perc', 'smartmeter_perc']

all_data = load_all_datasets(base_path, used_columns)

In [3]:
all_data.head()

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year,Type,Company
0,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Dorpsstraat,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1x35,4122.0,89.47,0.0,2018,Electricity,Coteq
1,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1x35,1800.0,94.59,0.0,2018,Electricity,Coteq
2,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1x35,1315.0,100.00,0.0,2018,Electricity,Coteq
3,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AD,7471AE,GOOR,25,92.00,84.00,44.0,1x35,6379.0,92.00,0.0,2018,Electricity,Coteq
4,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Kerkstraat,7471AG,7471AG,GOOR,14,85.71,100.00,36.0,1x35,4404.0,92.86,0.0,2018,Electricity,Coteq

In [4]:
all_data.isnull().sum()

net_manager                     0
purchase_area                   1
street                          0
zipcode_from                    1
zipcode_to                      0
city                            0
num_connections                 0
delivery_perc                   0
perc_of_active_connections      0
type_conn_perc                  0
type_of_connection              0
annual_consume                  0
annual_consume_lowtarif_perc    0
smartmeter_perc                 0
Year                            0
Type                            0
Company                         0
dtype: int64

In [5]:
all_data[all_data['purchase_area'].isnull()]

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year,Type,Company
156925,8716892000005,NaN,Groenelaan,3114CB,3114CB,SCHIEDAM,20,100.0,0.0,75.0,G4,1230.0,0.0,0.0,2018,Gas,Stedin

In [6]:
all_data[all_data['zipcode_from'].isnull()]

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year,Type,Company
21283,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Sportstraat,NaN,7165BD,WESTERHAAR-VRIEZENV WIJK,26,100.0,58.0,69.0,G4,3038.0,0.0,46.0,2020,Gas,Coteq

In [7]:
# fill by unknown 
all_data['zipcode_from'].fillna('unknown', inplace=True)
all_data['purchase_area'].fillna('unknown', inplace=True)

In [8]:
print('Unique net manager:\n',all_data['net_manager'].value_counts())
print('Unique purchase area:\n',all_data['purchase_area'].value_counts())

Unique net manager:
 8716892000005              258569
8716874000009              138395
8716886000004               37155
8716921000006               25348
Cogas Infra & Beheer BV     18897
westland-infra              14411
8716925000002                9328
Coteq Netbeheer BV           9277
8716892750009                9243
8716892700004                9225
8716892740000                9052
8716892710003                7778
8716892720002                5046
8716946000005                2026
8716924000003                  21
Name: net_manager, dtype: int64
Unique purchase area:
 Stedin                                    134726
Stedin Utrecht                             78542
NG Den Haag                                39895
Pseudo Gos Houten ENBU                     35539
Pseudo-GOS Dordrecht                       26342
GAS Gastransport Services (GASUNIE)        20533
Stedin Delfland                            20150
Pseudo-GOS Rotterdam                       19935
Pseudo Gos Hoogland ENBU                   14510
Stedin Midden-Holland                      13003
NG Leerdam                                 12976
Pseudo-GOS Zoetermeer                      10099
Pseudo Gos Veenendaal ENBU                 10070
NG Gouda                                    9661
Pseudo-GOS Zeist                            9243
NG Noord-Oost Friesland                     8615
Pseudo-GOS Amstelland                       8434
NG Hoekse waard                             8010
Pseudo-GOS Midden Kennemerland              7778
Netbeheerder Centraal Overijssel B.V.       7641
871687800090000015                          7399
871718518003006694                          7012
Pseudo-GOS Delft                            5803
Stedin Schiedam                             4775
NG Heemstede                                4660
Schiedam Kethel                             4552
Pseudo-GOS Vlaardingen                      3948
NG Brielle                                  3521
NG Waddinxveen                              2540
NG Krimpen                                  2532
Achterweg                                   2496
Stedin Elektriciteit Zuid-Kennemerland      2025
Maassluis                                   1630
Pseudo-GOS Bleiswijk                        1371
Oranjelaan                                   695
Hoek van Holland                             590
Ouderkerk ad Amstel                          558
Ameland                                      435
Halfweg                                      385
Ruigendijk                                   351
Moerseweg                                    337
Duivendrecht                                 234
Graswalseweg                                 182
Stedin Weert                                  16
Wildersekade                                  16
Pseudo-GOS Weert                               4
unknown                                        1
Weert Trancheeweg                              1
Name: purchase_area, dtype: int64

In [9]:
print("White space in the dataset")
def checkExtraWhiteSpace(ColName):
    Variable = [] 
    for anwser in all_data[ColName].unique():
        for Com_Val in str(anwser).split(";"):
            if (Com_Val in Variable): 
                break
            words = Com_Val.split(" ")
            if ("" in words):
                print("Column '{}', variable '{}' contains extra whitespace.".format(ColName, Com_Val)
                )
                Variable.append(Com_Val)
                break
for column in all_data.columns:
    if (str(all_data[column].dtypes) == "object"):
        checkExtraWhiteSpace(column)

White space in the dataset
Column 'street', variable 'Schoolstraat ' contains extra whitespace.
Column 'street', variable 'Papaverweg ' contains extra whitespace.
Column 'street', variable 'Brielsemeer ' contains extra whitespace.
Column 'street', variable 'Baandershof ' contains extra whitespace.
Column 'street', variable 'Enge IJsselweg ' contains extra whitespace.
Column 'street', variable 'Japansetuinlaan ' contains extra whitespace.
Column 'street', variable 'Valutaboulevard ' contains extra whitespace.
Column 'street', variable 'Engelenweide ' contains extra whitespace.
Column 'street', variable 'Hoekelumseboslaan ' contains extra whitespace.
Column 'street', variable 'Zwijnsbergen ' contains extra whitespace.

In [10]:
print(all_data['net_manager'].value_counts())

8716892000005              258569
8716874000009              138395
8716886000004               37155
8716921000006               25348
Cogas Infra & Beheer BV     18897
westland-infra              14411
8716925000002                9328
Coteq Netbeheer BV           9277
8716892750009                9243
8716892700004                9225
8716892740000                9052
8716892710003                7778
8716892720002                5046
8716946000005                2026
8716924000003                  21
Name: net_manager, dtype: int64

In [11]:
# apply street, city, purchase_area, net_manager to string 
all_data['street'] = all_data['street'].astype(str)
all_data['city'] = all_data['city'].astype(str)
all_data['purchase_area'] = all_data['purchase_area'].astype(str)
all_data['net_manager'] = all_data['net_manager'].astype(str)

In [12]:
# remove white space
all_data['street'] = all_data['street'].str.strip()
all_data['city'] = all_data['city'].str.strip()
all_data['purchase_area'] = all_data['purchase_area'].str.strip()
all_data['net_manager'] = all_data['net_manager'].str.strip()

In [13]:
all_data['net_manager'].replace({
    '8716892000005': 'Stedin B.V.',
    '8716874000009': 'Stedin B.V.',
    '8716892000005': 'Stedin B.V.',
    '8716886000004': 'Stedin B.V.',
    '8716874000009': 'Stedin B.V.',
    '8716886000004': 'Stedin B.V.',
    '8716921000006': 'Stedin B.V.',
    '8716921000006': 'Stedin B.V.',
    '8716946000005': 'Stedin B.V.',
    '8716946000005': 'Stedin B.V.',
    '8716925000002': 'Stedin B.V.',
    '8716892000005': 'Stedin B.V.',
    '8716892750009': 'Stedin B.V.',
    '8716892700004': 'Stedin B.V.',
    '8716892740000': 'Stedin B.V.',
    '8716892710003': 'Stedin B.V.',
    '8716892710003': 'Stedin B.V.',
    '8716892720002': 'Stedin B.V.',
    '8716924000003': 'Stedin B.V.',
}, inplace=True)

In [14]:
print(all_data['net_manager'].value_counts())

Stedin B.V.                511186
Cogas Infra & Beheer BV     18897
westland-infra              14411
Coteq Netbeheer BV           9277
Name: net_manager, dtype: int64

In [15]:
print(all_data['purchase_area'].value_counts())

Stedin                                    134726
Stedin Utrecht                             78542
NG Den Haag                                39895
Pseudo Gos Houten ENBU                     35539
Pseudo-GOS Dordrecht                       26342
GAS Gastransport Services (GASUNIE)        20533
Stedin Delfland                            20150
Pseudo-GOS Rotterdam                       19935
Pseudo Gos Hoogland ENBU                   14510
Stedin Midden-Holland                      13003
NG Leerdam                                 12976
Pseudo-GOS Zoetermeer                      10099
Pseudo Gos Veenendaal ENBU                 10070
NG Gouda                                    9661
Pseudo-GOS Zeist                            9243
NG Noord-Oost Friesland                     8615
Pseudo-GOS Amstelland                       8434
NG Hoekse waard                             8010
Pseudo-GOS Midden Kennemerland              7778
Netbeheerder Centraal Overijssel B.V.       7641
871687800090000015                          7399
871718518003006694                          7012
Pseudo-GOS Delft                            5803
Stedin Schiedam                             4775
NG Heemstede                                4660
Schiedam Kethel                             4552
Pseudo-GOS Vlaardingen                      3948
NG Brielle                                  3521
NG Waddinxveen                              2540
NG Krimpen                                  2532
Achterweg                                   2496
Stedin Elektriciteit Zuid-Kennemerland      2025
Maassluis                                   1630
Pseudo-GOS Bleiswijk                        1371
Oranjelaan                                   695
Hoek van Holland                             590
Ouderkerk ad Amstel                          558
Ameland                                      435
Halfweg                                      385
Ruigendijk                                   351
Moerseweg                                    337
Duivendrecht                                 234
Graswalseweg                                 182
Stedin Weert                                  16
Wildersekade                                  16
Pseudo-GOS Weert                               4
unknown                                        1
Weert Trancheeweg                              1
Name: purchase_area, dtype: int64

In [16]:
all_data['purchase_area'].replace({
    '871687800090000015': 'Westland Infra',
    '871718518003006694': 'Westland Infra',
}, inplace=True)
print(all_data['purchase_area'].value_counts())

Stedin                                    134726
Stedin Utrecht                             78542
NG Den Haag                                39895
Pseudo Gos Houten ENBU                     35539
Pseudo-GOS Dordrecht                       26342
GAS Gastransport Services (GASUNIE)        20533
Stedin Delfland                            20150
Pseudo-GOS Rotterdam                       19935
Pseudo Gos Hoogland ENBU                   14510
Westland Infra                             14411
Stedin Midden-Holland                      13003
NG Leerdam                                 12976
Pseudo-GOS Zoetermeer                      10099
Pseudo Gos Veenendaal ENBU                 10070
NG Gouda                                    9661
Pseudo-GOS Zeist                            9243
NG Noord-Oost Friesland                     8615
Pseudo-GOS Amstelland                       8434
NG Hoekse waard                             8010
Pseudo-GOS Midden Kennemerland              7778
Netbeheerder Centraal Overijssel B.V.       7641
Pseudo-GOS Delft                            5803
Stedin Schiedam                             4775
NG Heemstede                                4660
Schiedam Kethel                             4552
Pseudo-GOS Vlaardingen                      3948
NG Brielle                                  3521
NG Waddinxveen                              2540
NG Krimpen                                  2532
Achterweg                                   2496
Stedin Elektriciteit Zuid-Kennemerland      2025
Maassluis                                   1630
Pseudo-GOS Bleiswijk                        1371
Oranjelaan                                   695
Hoek van Holland                             590
Ouderkerk ad Amstel                          558
Ameland                                      435
Halfweg                                      385
Ruigendijk                                   351
Moerseweg                                    337
Duivendrecht                                 234
Graswalseweg                                 182
Wildersekade                                  16
Stedin Weert                                  16
Pseudo-GOS Weert                               4
unknown                                        1
Weert Trancheeweg                              1
Name: purchase_area, dtype: int64

### Then, split the dataset again

In [17]:
def split_dataset(df):
    # Split the dataset into train and test sets based on the specified criteria
    Etrain = df[(df['Type'] == 'Electricity') & (df['Year'].isin([2018, 2019]))]
    Etest = df[(df['Type'] == 'Electricity') & (df['Year'] == 2020)]
    Gtrain = df[(df['Type'] == 'Gas') & (df['Year'].isin([2018, 2019]))]
    Gtest = df[(df['Type'] == 'Gas') & (df['Year'] == 2020)]

    return Etrain, Etest, Gtrain, Gtest

# Example usage:
Etrain, Etest, Gtrain, Gtest = split_dataset(all_data)

In [18]:
# drop the Year, Company, Type columns
Etrain.drop(columns=['Year', 'Company', 'Type'], axis = 1)
Etest.drop(columns=['Year', 'Company', 'Type'], axis = 1)
Gtrain.drop(columns=['Year', 'Company', 'Type'], axis = 1)
Gtest.drop(columns=['Year', 'Company', 'Type'], axis = 1)

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc
21283,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Sportstraat,unknown,7165BD,WESTERHAAR-VRIEZENV WIJK,26,100.0,58.0,69.0,G4,3038.0,0.0,46.00
21284,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Oude Deldenseweg,7165BG,7216PN,RIETMOLEN,18,100.0,100.0,78.0,G4,3895.0,0.0,67.00
21285,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Wippertdijk,7216PP,7245TG,KRING VAN DORTH,121,100.0,98.0,73.0,G4,3355.0,0.0,65.00
21286,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Warfveendijk,7245TH,7245TP,LAREN GLD,27,100.0,96.0,56.0,G4,3013.0,0.0,56.00
21287,Cogas Infra & Beheer BV,GAS Gastransport Services (GASUNIE),Kielersdijk,7245TS,7275AZ,LAREN GLD,81,100.0,100.0,79.0,G4,2240.0,0.0,59.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553766,westland-infra,Westland Infra,IN DE BALIJE,3155XA,3155XA,MAASLAND,14,100.0,100.0,79.0,G4,3035.0,0.0,85.71
553767,westland-infra,Westland Infra,KONINGIN JULIANAWEG,3155XB,3155XB,MAASLAND,14,100.0,100.0,86.0,G4,2744.0,0.0,92.86
553768,westland-infra,Westland Infra,KONINGIN JULIANAWEG,3155XC,3155XD,MAASLAND,27,100.0,100.0,93.0,G4,2903.0,0.0,77.78
553769,westland-infra,Westland Infra,KONINGIN JULIANAWEG,3155XE,3155XH,MAASLAND,28,100.0,100.0,86.0,G4,1741.0,0.0,53.57
553770,westland-infra,Westland Infra,MERESTEIJN,3155XJ,3155XK,MAASLAND,19,100.0,100.0,100.0,G4,3163.0,0.0,47.37

In [19]:
# save to csv
Etrain.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Train.csv', index=False)
Etest.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Test.csv', index=False)
Gtrain.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2//As2-EEET574/Merged_dataset/Gas/G-Train.csv', index=False)
Gtest.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/G-Test.csv', index=False)