
#### Transform the feature of train dataset (yah to train) for both gas and Electricity

### Todo: metrics visulization, transformation 
##### One-hot encoding: a process of converting categorical variables into binary vectors, where each category becomes a separate binary vector.
- A -> [1,0,0]
- B -> [0,1,0]
- C -> [0,0,1]
##### Label encoding is a process of assigning a unique integer value to each category in a categorical column.
- A -> 0
- B -> 1
- C -> 2
--> todo : 
- data visualization
- categorical : label encoding
- for zipcode: one-hot encoding 
- ordinal data
- data normalization 
#### While Nominal Data is classified without any intrinsic ordering or rank, Ordinal Data has some predetermined or natural order. Nominal data is qualitative or categorical data, while Ordinal data is considered “in-between” qualitative and quantitative data
--> clean, transform, split, model 
- fe>>model selection>>training>>validate
- Correlation between electricity consumption and other variables:
- annual_consumption by street
- annual_consumption by zip code (lam sao ta)
- A bar chart/line graph could be used to show the adoption rate of smart meters over time.
- we can consider smarmeter_perc as categorical dtypes
--> transform by each column

### --> Observations: 
- considered net_manager, purchase_area, street and city are categorical column (we have to train by year and there are differences companies and purchase area)
- Since zipcode_from and zipcode_to contains unique zipcode I will work with that later
- One more categorical column is type_of_connection, check later
- the zipcode will be transfered later, so replace NaN value by Unknown

- According to Noord-Brabant, The "s-" at the beginning of some Dutch city names is a contraction of the Dutch word "des" which means "the" in English. It is a remnant of older Dutch grammar and is used to indicate possession or association with a particular noble family or lord. In the case of 's-Hertogenbosch, it refers to the Duke of Brabant
https://www.eur.nl/sites/corporate/files/Thesis_Straatnamen_Kooloos.pdf
- However, '-' and " ' " should be replaced when it turns to feature extraction --> replace by whitespace 
- the ```STANDAARDDEVIATIE``` column is not in the description --> remove
#### The id columns is currently id, we should change it into net_manager name for matching the given dataset 
##### Based on information from netbeheer, those id stands for Stedin B.V company. -> Apply company name to the column

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
Etrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/Etrain_cleaned.csv')
Etrain.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_33796\3832106797.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  Etrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/Etrain_cleaned.csv')

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year
0,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DORPSSTRAAT,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1X35,4122.0,89.47,0.0,2018
1,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1X35,1800.0,94.59,0.0,2018
2,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1X35,1315.0,100.00,0.0,2018
3,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AD,7471AE,GOOR,25,92.00,84.00,44.0,1X35,6379.0,92.00,0.0,2018
4,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,KERKSTRAAT,7471AG,7471AG,GOOR,14,85.71,100.00,36.0,1X35,4404.0,92.86,0.0,2018

In [6]:
# the annual_consume is regression problem, so I will split  the data into 2 parts: train and test
Xetrain = Etrain.drop(['annual_consume'], axis=1)
Yetrain = Etrain['annual_consume']