### Data cleaning 
- open Gas and Electricity dataset
- clean
- save

In [29]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
# open the train dataset 
Etrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Train.csv')
Etest = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Test.csv')    
Etrain.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_23620\1232393341.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  Etrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Train.csv')
C:\Users\Admin\AppData\Local\Temp\ipykernel_23620\1232393341.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  Etest = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/E-Test.csv')

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year,Type,STANDAARDDEVIATIE,%Defintieve aansl (NRM)
0,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Dorpsstraat,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1x35,4122.0,89.47,0.0,2018,Electricity,NaN,NaN
1,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1x35,1800.0,94.59,0.0,2018,Electricity,NaN,NaN
2,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1x35,1315.0,100.00,0.0,2018,Electricity,NaN,NaN
3,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AD,7471AE,GOOR,25,92.00,84.00,44.0,1x35,6379.0,92.00,0.0,2018,Electricity,NaN,NaN
4,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Kerkstraat,7471AG,7471AG,GOOR,14,85.71,100.00,36.0,1x35,4404.0,92.86,0.0,2018,Electricity,NaN,NaN

In [31]:
Etest.head()

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year,Type,STANDAARDDEVIATIE,%Defintieve aansl (NRM)
0,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,Dorpsstraat,7468CP,7471AA,ENTER,19,89.0,95.0,89.0,1x35,3810.0,89.0,89.0,2020,Electricity,NaN,NaN
1,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AB,7471AB,GOOR,40,100.0,98.0,78.0,1x35,2637.0,95.0,83.0,2020,Electricity,NaN,NaN
2,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AC,7471AC,GOOR,16,100.0,100.0,100.0,1x35,1366.0,100.0,94.0,2020,Electricity,NaN,NaN
3,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AD,7471AE,GOOR,41,93.0,85.0,54.0,3x25,5101.0,93.0,78.0,2020,Electricity,NaN,NaN
4,Cogas Infra & Beheer BV,Netbeheerder Centraal Overijssel B.V.,Kerkstraat,7471AG,7471AG,GOOR,14,86.0,100.0,36.0,1x25,4315.0,100.0,93.0,2020,Electricity,NaN,NaN

### Drop the unsuitable columns

In [32]:
# # drop the STANDAARDDEVIATIE and %Defintieve aansl (NRM) columns
Etrain = Etrain.drop(['STANDAARDDEVIATIE', '%Defintieve aansl (NRM)','Type'], axis=1)
Etest = Etest.drop(['STANDAARDDEVIATIE', '%Defintieve aansl (NRM)','Type'], axis=1)
Etrain.head()

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year
0,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Dorpsstraat,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1x35,4122.0,89.47,0.0,2018
1,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1x35,1800.0,94.59,0.0,2018
2,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1x35,1315.0,100.00,0.0,2018
3,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,De Stoevelaar,7471AD,7471AE,GOOR,25,92.00,84.00,44.0,1x35,6379.0,92.00,0.0,2018
4,Coteq Netbeheer BV,Netbeheerder Centraal Overijssel B.V.,Kerkstraat,7471AG,7471AG,GOOR,14,85.71,100.00,36.0,1x35,4404.0,92.86,0.0,2018

In [33]:
print('Unique net manager for Etrain :\n',Etrain['net_manager'].value_counts())
print('Unique net manager for Etest :\n',Etest['net_manager'].value_counts())
print('Unique purchase area for Etrain :\n',Etrain['purchase_area'].value_counts())
print('Unique purchase area for Etest :\n',Etest['purchase_area'].value_counts())

Unique net manager for Etrain :
 8716892000005              71172
8716874000009              45016
8716892000005              18094
8716886000004               6710
8716874000009               6419
8716886000004               6363
westland-infra              4842
8716921000006               4703
8716921000006               3925
8716925000002               3146
Cogas Infra & Beheer BV     2563
Coteq Netbeheer BV          2503
8716946000005                670
8716946000005                661
8716924000003                 11
8716924000003                  5
8716925000002                  4
Name: net_manager, dtype: int64
Unique net manager for Etest :
 8716892000005              25477
8716874000009              21407
8716892000005              20368
8716886000004               6813
8716874000009               5466
8716921000006               4286
Cogas Infra & Beheer BV     2575
westland-infra              2557
8716925000002               1625
8716946000005                695
8716921000006                193
8716886000004                  7
8716925000002                  1
Name: net_manager, dtype: int64
Unique purchase area for Etrain :
 Stedin                                    88881
Stedin Utrecht                            51669
Stedin Delfland                           13330
Stedin Midden-Holland                      8524
Netbeheerder Centraal Overijssel B.V.      5066
871687800090000015                         4842
Stedin Schiedam                            3149
Stedin Elektriciteit Zuid-Kennemerland     1330
Stedin Weert                                 16
Name: purchase_area, dtype: int64
Unique purchase area for Etest :
 Stedin                                    45845
Stedin Utrecht                            26873
Stedin Delfland                            6820
Stedin Midden-Holland                      4479
Netbeheerder Centraal Overijssel B.V.      2575
871687800090000015                         2557
Stedin Schiedam                            1626
Stedin Elektriciteit Zuid-Kennemerland      695
Name: purchase_area, dtype: int64

In [34]:
print("White space in the train dataset")
def checkExtraWhiteSpace(ColName):
    Variable = [] 
    for anwser in Etrain[ColName].unique():
        for Com_Val in str(anwser).split(";"):
            if (Com_Val in Variable): 
                break
            words = Com_Val.split(" ")
            if ("" in words):
                print("Column '{}', variable '{}' contains extra whitespace.".format(ColName, Com_Val)
                )
                Variable.append(Com_Val)
                break
for column in Etrain.columns:
    if (str(Etrain[column].dtypes) == "object"):
        checkExtraWhiteSpace(column)
print("for testing dataset")
def checkExtraWhiteSpace(ColName):
    Variable = [] 
    for anwser in Etest[ColName].unique():
        for Com_Val in str(anwser).split(";"):
            if (Com_Val in Variable): 
                break
            words = Com_Val.split(" ")
            if ("" in words):
                print("Column '{}', variable '{}' contains extra whitespace.".format(ColName, Com_Val)
                )
                Variable.append(Com_Val)
                break
for column in Etest.columns:
    if (str(Etest[column].dtypes) == "object"):
        checkExtraWhiteSpace(column)

White space in the train dataset
Column 'street', variable 'Schoolstraat ' contains extra whitespace.
Column 'street', variable 'Papaverweg ' contains extra whitespace.
Column 'street', variable 'Brielsemeer ' contains extra whitespace.
Column 'street', variable 'Baandershof ' contains extra whitespace.
Column 'street', variable 'Enge IJsselweg ' contains extra whitespace.
Column 'street', variable 'Japansetuinlaan ' contains extra whitespace.
Column 'street', variable 'Valutaboulevard ' contains extra whitespace.
Column 'street', variable 'Engelenweide ' contains extra whitespace.
for testing dataset
Column 'street', variable 'Schoolstraat ' contains extra whitespace.
Column 'street', variable 'Papaverweg ' contains extra whitespace.
Column 'street', variable 'Brielsemeer ' contains extra whitespace.
Column 'street', variable 'Baandershof ' contains extra whitespace.
Column 'street', variable 'Hoekelumseboslaan ' contains extra whitespace.
Column 'street', variable 'Japansetuinlaan ' contains extra whitespace.
Column 'street', variable 'Enge IJsselweg ' contains extra whitespace.
Column 'street', variable 'Engelenweide ' contains extra whitespace.
Column 'street', variable 'Zwijnsbergen ' contains extra whitespace.
Column 'street', variable 'Valutaboulevard ' contains extra whitespace.

In [35]:
# remove the whitespace in the columns
Etrain['street'] = Etrain['street'].str.strip()
Etest['street'] = Etest['street'].str.strip()

In [36]:
# apply uppercase to all object columns since they are mostly unique
def uppercaseAllObjectColumns(dataframe):
    for column in dataframe.columns:
        if (str(dataframe[column].dtypes) == "object"):
            dataframe[column] = dataframe[column].str.upper()
            
uppercaseAllObjectColumns(Etrain)
uppercaseAllObjectColumns(Etest)
Etrain.head(3)

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year
0,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DORPSSTRAAT,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1X35,4122.0,89.47,0.0,2018
1,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1X35,1800.0,94.59,0.0,2018
2,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1X35,1315.0,100.00,0.0,2018

###  I have checked the dataset, and commonly there are only 1 or 2 typo and there is no typo in city

In [37]:
Ecity = Etrain['city'].value_counts()
Ecity = Ecity[Ecity == 1]
# Ecity = Ecity[Ecity == 2]
Ecity

HILVERSUM                 1
'SÂGRAVENHAGE           1
AMSTELVEEN                1
MAURIK                    1
BUSSUM                    1
DEN HOORN                 1
WASSENAAR                 1
NIEUWGEIN                 1
HARDINXVELD GIESSENDAM    1
CULEMBORG                 1
GROOT AMMERS              1
'S GRAVENHAGE             1
ZEVENHOVEN                1
Name: city, dtype: int64

In [38]:
Etestcity = Etest['city'].value_counts()
Etestcity = Etestcity[Etestcity == 1]
Ecity

HILVERSUM                 1
'SÂGRAVENHAGE           1
AMSTELVEEN                1
MAURIK                    1
BUSSUM                    1
DEN HOORN                 1
WASSENAAR                 1
NIEUWGEIN                 1
HARDINXVELD GIESSENDAM    1
CULEMBORG                 1
GROOT AMMERS              1
'S GRAVENHAGE             1
ZEVENHOVEN                1
Name: city, dtype: int64

In [39]:
# replace 'SÂGRAVENHAGE by 'S GRAVENHAGE
Etrain['city'] = Etrain['city'].str.replace('SÂGRAVENHAGE', 'S GRAVENHAGE')
Etest['city'] = Etest['city'].str.replace('SÂGRAVENHAGE', 'S GRAVENHAGE')

#### Clean Gas dataset

In [40]:
# open gas 
Gtrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/G-Train.csv',
                     usecols=['net_manager', 'purchase_area', 'street', 'zipcode_from', 'zipcode_to', 'city', 'delivery_perc', 'num_connections', 'perc_of_active_connections', 'type_conn_perc', 'type_of_connection', 'annual_consume', 'annual_consume_lowtarif_perc', 'smartmeter_perc','Year'])
Gtest = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/G-Test.csv',
                     usecols=['net_manager', 'purchase_area', 'street', 'zipcode_from', 'zipcode_to', 'city', 'delivery_perc', 'num_connections', 'perc_of_active_connections', 'type_conn_perc', 'type_of_connection', 'annual_consume', 'annual_consume_lowtarif_perc', 'smartmeter_perc','Year'])

Gtrain.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_23620\3225199425.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  Gtrain = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/G-Train.csv',
C:\Users\Admin\AppData\Local\Temp\ipykernel_23620\3225199425.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  Gtest = pd.read_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/G-Test.csv',

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year
0,Coteq Netbeheer BV,GAS Gastransport Services (GASUNIE),Margrietstraat,4175GA,7165BD,HAAFTEN,18,100.0,83.33,78.0,G4,3457.0,0.0,0.0,2018
1,Coteq Netbeheer BV,GAS Gastransport Services (GASUNIE),Oude Deldenseweg,7165BG,7216PN,RIETMOLEN,17,100.0,100.00,76.0,G4,4036.0,0.0,0.0,2018
2,Coteq Netbeheer BV,GAS Gastransport Services (GASUNIE),Wippertdijk,7216PP,7245TG,KRING VAN DORTH,117,100.0,100.00,71.0,G4,3695.0,0.0,0.0,2018
3,Coteq Netbeheer BV,GAS Gastransport Services (GASUNIE),Warfveendijk,7245TH,7245TP,LAREN GLD,26,100.0,100.00,62.0,G4,3307.0,0.0,0.0,2018
4,Coteq Netbeheer BV,GAS Gastransport Services (GASUNIE),Kielersdijk,7245TS,7275AZ,LAREN GLD,81,100.0,97.53,78.0,G4,2306.0,0.0,0.0,2018

In [41]:
# count the number of unique values in each column
for column in Gtrain.columns:
    print(column, Gtrain[column].nunique())

net_manager 24
purchase_area 38
street 31598
zipcode_from 95617
zipcode_to 95087
city 491
num_connections 224
delivery_perc 4
perc_of_active_connections 941
type_conn_perc 79
type_of_connection 6
annual_consume 6405
annual_consume_lowtarif_perc 1
smartmeter_perc 2393
Year 2

In [42]:
print("For Gas train dataset")
def checkExtraWhiteSpace(ColName):
    Variable = [] 
    for anwser in Gtrain[ColName].unique():
        for Com_Val in str(anwser).split(";"):
            if (Com_Val in Variable): 
                break
            words = Com_Val.split(" ")
            if ("" in words):
                print("Column '{}', variable '{}' contains extra whitespace.".format(ColName, Com_Val)
                )
                Variable.append(Com_Val)
                break
for column in Gtrain.columns:
    if (str(Gtrain[column].dtypes) == "object"):
        checkExtraWhiteSpace(column)
print("for Gas test dataset")

def checkExtraWhiteSpace(ColName):
    Variable = [] 
    for anwser in Gtest[ColName].unique():
        for Com_Val in str(anwser).split(";"):
            if (Com_Val in Variable): 
                break
            words = Com_Val.split(" ")
            if ("" in words):
                print("Column '{}', variable '{}' contains extra whitespace.".format(ColName, Com_Val)
                )
                Variable.append(Com_Val)
                break
for column in Gtest.columns:
    if (str(Gtest[column].dtypes) == "object"):
        checkExtraWhiteSpace(column)

For Gas train dataset
Column 'street', variable 'Baandershof ' contains extra whitespace.
for Gas test dataset
Column 'street', variable 'Baandershof ' contains extra whitespace.

In [43]:
# remove the whitespace in the columns
Gtrain['street'] = Gtrain['street'].str.strip()
Gtest['street'] = Gtest['street'].str.strip()

In [44]:
# apply uppercase to all object columns since they are mostly unique
def uppercaseAllObjectColumns(dataframe):
    for column in dataframe.columns:
        if (str(dataframe[column].dtypes) == "object"):
            dataframe[column] = dataframe[column].str.upper()
            
uppercaseAllObjectColumns(Etrain)
uppercaseAllObjectColumns(Etest)
Etrain.head(3)

,net_manager,purchase_area,street,zipcode_from,zipcode_to,city,num_connections,delivery_perc,perc_of_active_connections,type_conn_perc,type_of_connection,annual_consume,annual_consume_lowtarif_perc,smartmeter_perc,Year
0,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DORPSSTRAAT,7468CP,7471AA,ENTER,19,89.47,94.74,89.0,1X35,4122.0,89.47,0.0,2018
1,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AB,7471AB,GOOR,37,100.00,100.00,86.0,1X35,1800.0,94.59,0.0,2018
2,COTEQ NETBEHEER BV,NETBEHEERDER CENTRAAL OVERIJSSEL B.V.,DE STOEVELAAR,7471AC,7471AC,GOOR,16,100.00,100.00,100.0,1X35,1315.0,100.00,0.0,2018

In [45]:
# save the cleaned dataset to csv
Etrain.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/Etrain_cleaned.csv', index=False)
Etest.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Electricity/Etest_cleaned.csv', index=False)
Gtrain.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/Gtrain_cleaned.csv', index=False)
Gtest.to_csv('C:/TaiLieuHocTap/RMIT/C-2023/BigData/asignment2/As2-EEET574/Merged_dataset/Gas/Gtest_cleaned.csv', index=False)